### ISSUE TITLE
isatty error

### ISSUE THREAD

**Issue by ghost** [quanganhquanganh/Anki-Youtube-Audio-Miner#1]
Hello!
I'm getting an error as soon as I've pressed Download audio
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.45 (355e66e8) Python 3.9.6 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-08-03 10:02:28
Add-ons possibly involved: ⁨Youtube Audio Miner⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/main.py", line 114, in run
    ydl.download([self.href])
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/extractor/youtube.py", line 1486, in _real_extract
    player_response = self._extract_yt_initial_variable(
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/extractor/youtube.py", line 1472, in _extract_yt_initial_variable
    return self._parse_json(self._search_regex(
  File "/home/yannicko/.local/share/Anki2/addons21/1186808928/youtube_dl/extractor/common.py", line 998, in _search_regex
    if not self._downloader.params.get('no_color') and compat_os_name != 'nt' and sys.stderr.isatty():
AttributeError: 'ErrorHandler' object has no attribute 'isatty'

```

**Comment by quanganhquanganh** [comment]
Hi thanks for sending the issue. Sorry for the late reply lol, this is my first one so yeah :D. 
I'll check and see what I can do.

**Comment by quanganhquanganh** [comment]
Hi it seems like I got the same error when I clicked on the button twice. Is the download bar full in your case?

**Comment by ghost** [comment]
Hey! Nope, it stays at 0% and throws an error as soon as I press download.
![image](https://user-images.githubusercontent.com/30667087/128372202-3e11c3aa-1022-429c-853e-9759312da231.png)

**Comment by quanganhquanganh** [comment]
Hi do other videos show the same errors that you got here? I tried the link inside the screenshot and for some reason youtube dl couldn't get the subtitles.

**Comment by ghost** [comment]
I tried with french videos, japanese videos and chinese videos and none of them worked :(

**Comment by quanganhquanganh** [comment]
Hi I think I've fixed the bug. Seems like my version of youtube-dl didn't work on Linux for some reason.
Sorry for the super late fix, been quite busy for the last 2 weeks or so.
